### ISSUE TITLE
can't install on windows PC: localhost, Drupal 7.5

### ISSUE THREAD

**Issue by olevine** [cirlabs/impact-tracker#1]
Hi,
I work at ICFJ, and want to install the Tracker locally. I am running a LAMP stack on my laptop, and want to install the tracker to Drupal 7.5. I'm seeing an error 'Sorry, the profile you have chosen cannot be loaded." 
Any thoughts on what may be happening? I'm reasonably familiar with web servers, but new to Drupal. 
Thanks!
-Oren Levine, Director of Innovation, ICFJ

**Comment by Lab43** [comment]
Hi Oren,

Did you follow the instructions at https://github.com/cirlabs/impact-tracker, including using Drush to install dependencies? At what point do you get the error message? Is that something Drush gives you, or is it something Drupal shows you?

Just to verify, you're working on windows? I haven't personally tested install the site on Windows. 

-Cameron

**Comment by olevine** [comment]
Thanks Cameron,
Yes, I'm working on Windows, and did not use Drush after reading about problems with that tool on Windows. Instead. I installed AMPPS, an integrated LAMP stack, and tried to follow the Drupal instructions for installing from a package, after a separate install of Drupal. 
What I'm going to try now is Drush in that LAMP environment.

**Comment by Lab43** [comment]
Drush is needed to install all the dependencies. You could try installing all the modules and patches listed in https://github.com/cirlabs/impact-tracker/blob/master/impact_tracker.make by hand.

**Comment by Lab43** [comment]
Hi Oren,

I'm going to close this issue. Feel free to reopen it if you're still having trouble.

By the way, I put together a short video to help people who are new to Drupal to install the Impact Tracker: [https://www.youtube.com/watch?v=RO_1g8S4zNs](https://www.youtube.com/watch?v=RO_1g8S4zNs)

Thanks,
Cameron

**Comment by olevine** [comment]
Thanks, Cameron. 
I watched the video, but on Windows 10 the process breaks down at the first step. I download the Tracker and install drush, run the makefile and see this:

C:\impact-tracker-master>drush make impact-tracker.make
Make new site in the current directory? (y/n): y
 [warning] file_get_contents(impact-tracker.make): failed to open stream: No such file or directory make.utilities.inc:577
 [error]  Invalid or empty make file: impact-tracker.make
 [notice] Beginning to build impact-tracker.make.
 [error]  No core project specified.
 [error]  Drush Make failed to download all projects. See the log above for the specific errors.

Happy to hear any thoughts about how to resolve this.

**Comment by Lab43** [comment]
Hi Oren,

It might just be a typo. It should be impact_tracker.make, with an underscore.

-Cameron
