### ISSUE TITLE
Add more details to documentation

### ISSUE THREAD

**Issue by miguelpaz** [cirlabs/impact-tracker#2]
Since Drupla is not widely used in small newsrooms specially (the sort of media organization that would benefit from using Impact Tracker) it would be great if you can:
-[ ] add detailed install, setup and troubleshooting documentation
-[ ] add a wiki with details about Impact Tracker and screenshots: features, workflow, etc.
Thanks for releasing the code!

**Comment by miguelpaz** [comment]
I meant Drupal

**Comment by Lab43** [comment]
Hi Miguel,

You're right, the installation documentation is pretty incomplete. Not sure how soon I'll be able to write up more detailed documentation, so for the time being I made a short video to walk people through the installation process if they are not already familiar with Drupal development.

Here it is: [https://www.youtube.com/watch?v=RO_1g8S4zNs](https://www.youtube.com/watch?v=RO_1g8S4zNs)

Thanks,
Cameron
