### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by freejoe76** [cirlabs/impact-tracker#4]
Hi!

I'm not that fluent in Drupal, so when I went through the instructions on your README I stumbled on step three:

> Install Drupal as normal.

The link on that step implied to me that I needed to create a separate Drupal installation, instead of simply navigating to the impact-tracker's directory on my web browser (after putting impact-tracker below my web root) and following the installation wizard there.

Joe

**Comment by freejoe76** [comment]
Wait wait wait, I didn't provide the improvement: I'd go with this language for step three instead:

> Make sure the impact tracker directory is somewhere at or below your web root, and open up the impact tracker directory in your web browser. Run the Drupal installation from there.

**Comment by Lab43** [comment]
Hi Joe,

I'm not sure you're setting up the site the way I intended. I created a YouTube tutorial for someone else that was having trouble. It's linked here: https://github.com/cirlabs/impact-tracker/issues/1#issuecomment-236464224

Does this match what you're doing?

Thanks,
Cameron

**Comment by Lab43** [comment]
Here's a direct link to the video: https://www.youtube.com/watch?v=RO_1g8S4zNs

**Comment by freejoe76** [comment]
Hi! I installed it the way described in the video, I was just pointing out that step three, to me, implied I ought to download Drupal and install it adjacent to the cir lab files and all that, which wasn't the thing to do at all.

**Comment by Lab43** [comment]
He Joe,

I clarified that step in the instructions and added the YouTube tutorial to the readme. Let me know if this fixes the issue.

-Cameron

**Comment by freejoe76** [comment]
I'm totally cool with that! Thanks~~~~~~
